// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_image_converters/test/domain/usecases/convert_and_save_images_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:typed_data' as _i8;

import 'package:flutter_image_converters/core/services/image_service.dart'
    as _i3;
import 'package:flutter_image_converters/core/services/permission_service.dart'
    as _i9;
import 'package:flutter_image_converters/presentation/models/conversion_settings.dart'
    as _i5;
import 'package:flutter_image_converters/presentation/models/image_data.dart'
    as _i2;
import 'package:flutter_image_converters/presentation/models/resize_setting.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeImageData_0 extends _i1.SmartFake implements _i2.ImageData {
  _FakeImageData_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ImageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockImageService extends _i1.Mock implements _i3.ImageService {
  @override
  _i4.Future<_i2.ImageData?> pickImage() => (super.noSuchMethod(
        Invocation.method(
          #pickImage,
          [],
        ),
        returnValue: _i4.Future<_i2.ImageData?>.value(),
        returnValueForMissingStub: _i4.Future<_i2.ImageData?>.value(),
      ) as _i4.Future<_i2.ImageData?>);

  @override
  _i4.Future<List<_i2.ImageData>> pickMultipleImages() => (super.noSuchMethod(
        Invocation.method(
          #pickMultipleImages,
          [],
        ),
        returnValue: _i4.Future<List<_i2.ImageData>>.value(<_i2.ImageData>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i2.ImageData>>.value(<_i2.ImageData>[]),
      ) as _i4.Future<List<_i2.ImageData>>);

  @override
  _i4.Future<_i2.ImageData> convertImage(
    _i2.ImageData? sourceImage,
    _i5.ConversionSettings? settings,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #convertImage,
          [
            sourceImage,
            settings,
          ],
        ),
        returnValue: _i4.Future<_i2.ImageData>.value(_FakeImageData_0(
          this,
          Invocation.method(
            #convertImage,
            [
              sourceImage,
              settings,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.ImageData>.value(_FakeImageData_0(
          this,
          Invocation.method(
            #convertImage,
            [
              sourceImage,
              settings,
            ],
          ),
        )),
      ) as _i4.Future<_i2.ImageData>);

  @override
  _i4.Future<_i2.ImageData> resizeImage(
    _i2.ImageData? sourceImage,
    _i6.ResizeSettings? settings,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #resizeImage,
          [
            sourceImage,
            settings,
          ],
        ),
        returnValue: _i4.Future<_i2.ImageData>.value(_FakeImageData_0(
          this,
          Invocation.method(
            #resizeImage,
            [
              sourceImage,
              settings,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.ImageData>.value(_FakeImageData_0(
          this,
          Invocation.method(
            #resizeImage,
            [
              sourceImage,
              settings,
            ],
          ),
        )),
      ) as _i4.Future<_i2.ImageData>);

  @override
  _i4.Future<String> saveImage(
    _i2.ImageData? imageData,
    String? directory,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveImage,
          [
            imageData,
            directory,
          ],
        ),
        returnValue: _i4.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #saveImage,
            [
              imageData,
              directory,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #saveImage,
            [
              imageData,
              directory,
            ],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<_i8.Uint8List> getThumbnail(
    _i2.ImageData? imageData, {
    int? maxSize = 200,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getThumbnail,
          [imageData],
          {#maxSize: maxSize},
        ),
        returnValue: _i4.Future<_i8.Uint8List>.value(_i8.Uint8List(0)),
        returnValueForMissingStub:
            _i4.Future<_i8.Uint8List>.value(_i8.Uint8List(0)),
      ) as _i4.Future<_i8.Uint8List>);

  @override
  void clearThumbnailCache() => super.noSuchMethod(
        Invocation.method(
          #clearThumbnailCache,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [PermissionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPermissionService extends _i1.Mock implements _i9.PermissionService {
  @override
  _i4.Future<bool> requestStoragePermission() => (super.noSuchMethod(
        Invocation.method(
          #requestStoragePermission,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}
